name: fastap
description: "FasTap revolutionizes professional networking by enabling users to share contact details and social media links instantly via NFC cards and QR codes, ensuring efficient and eco-friendly connections"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  


###### ================ UI ================= ######
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  lottie: ^2.2.0
  qr_flutter: ^4.1.0
  

  

  ###### ================ DATA SOURCE ================= ######
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0 
  url_launcher: ^6.2.6
  dio: ^5.4.3+1

  ###### ================ Utils ================= ######
  image_picker: 
  flutter_share: ^2.0.0
  # palestine_connection: ^0.0.21
  # in_app_review: ^2.0.8
  
  ###### ================ Firebase ================= ######
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: 
  # flutter_facebook_auth: ^6.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1

  # -------- App Icon Launcher ----------#
  flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true

#   image_path: "assets/app_logo/app_logo.png"
#   remove_alpha_ios: true

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/animations/

  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Inter-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Inter-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/Inter-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Thin.ttf
  #         weight: 100
